version: "2.3"

services:
  cornernet_lite:
    build: "."
    runtime: nvidia
    restart: "no"
    command: ./entrypoint.sh CornerNet_Lite CornerNet_Squeeze
    volumes:
      - /home/tanderson/models/datasets/mscoco/raw-data/cornernet_lite/:/CornerNet-Lite/data/coco/annotations
      - /home/tanderson/models/datasets/mscoco/raw-data/generated_split/train/:/CornerNet-Lite/data/coco/images/trainval2014
      - /home/tanderson/models/datasets/mscoco/raw-data/generated_split/val/:/CornerNet-Lite/data/coco/images/minival2014
      - /home/tanderson/models/datasets/mscoco/raw-data/test2017/:/CornerNet-Lite/data/coco/images/testdev2017
      - /home/tanderson/models/runs/cornernet_lite:/CornerNet-Lite/cache